version: 2.1
jobs:
  build:
    docker:
      - image: monacoremo/nix:2020-01-14-f9c81b5c-circleci
    steps:
      - checkout
      - run:
          name: Pre-load Nix environment
          command: nix-shell --run "echo Loaded the Nix environment"
      - run:
          name: Set up the test result directory structure
          command: mkdir -p test-results/{pgtap}
      - run:
          name: Grant access to the non-root test user
          command: |
            # There must be a better way to do this...
            chown -R user:user /root/project
            chmod o+xr /root /root/project
      - run:
          name: Run tests
          command: |
            nix-shell --run 'exit' 
      - store_test_results:
            path: test-results
